services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_wallet_dev
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
