services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_wallet_dev
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digital_wallet_dev"]
      interval: 5s
      timeout: 5s
      retries: 5